# Sharemind SecreC environment YAML file
name: DiffPrivacywithSMC
# List of dependencies required to run the Sharemind SecreC code
dependencies:
  - stdlib # Sharemind SecreC standard library
  - shared3p  # Sharemind 3-party library for common functionalities
  - shared3p_random  # Sharemind 3-party library for random number generation
  - shared3p_sort  # Sharemind 3-party library for sorting functionalities
  - sharemind_sdk # Sharemind SDK emulator for running SecreC code on VirtualBox

---
# .yml file for the ipynb notebook is as follows
kernel:
  name: python3  

libraries:
- name: numpy
  version: "*"  
- name: matplotlib
  version: "*"
...